name: build-and-publish-docker-images

on:
  push:
    branches: [ "master", "v2" ]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3.3.0
    - run: CGO_ENABLED=0 GOOS=linux go build . -a -o amd64/home-hub
